name: Terraform EC2 Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: |
        terraform plan \
          -var "aws_region=${{ secrets.AWS_REGION }}" \
          -var "ami_id=${{ secrets.AMI_ID }}" \
          -var "instance_type=t2.micro" \
          -var "key_name=${{ secrets.KEY_NAME }}" \
          -var "subnet_id=${{ secrets.SUBNET_ID }}" \
          -var "security_group_id=${{ secrets.SECURITY_GROUP_ID }}"

    - name: Terraform Apply
      run: |
        terraform apply -auto-approve \
          -var "aws_region=${{ secrets.AWS_REGION }}" \
          -var "ami_id=${{ secrets.AMI_ID }}" \
          -var "instance_type=t2.micro" \
          -var "key_name=${{ secrets.KEY_NAME }}" \
          -var "subnet_id=${{ secrets.SUBNET_ID }}" \
          -var "security_group_id=${{ secrets.SECURITY_GROUP_ID }}"
